name: test

on: [ push, pull_request ]

jobs:
  test:
    name: Node v${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        node: [ '16', '18', '20' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: denoland/setup-deno@v1
      #  with:
      #    deno-version: v1.x
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm install
      - name: Run lint
        run: npm run lint
      - name: Check for circular imports
        run: npm run check
      - name: Run tests
        run: npm run citest
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          PGUSER: postgres
          PGSOCKET: /var/run/postgresql
          PGDATABASE: postgrejs_test
          INIT_PG: true
          LOGIN_MD5: postgrejs_test_md5
          LOGIN_SCRAM: postgrejs_test_scram
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
