name: test

on: [ push, pull_request ]

jobs:
  test:
    name: Node v${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        node: [ '18', '20', '22' ]
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # - uses: denoland/setup-deno@v1
      #  with:
      #    deno-version: v1.x

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install NodeJS dependencies
        run: npm ci

      - name: Run linter test
        run: npm run lint

      - name: Run circular dependency test
        run: npm run check

      - name: Run compile test
        run: npm run compile

      - name: Run unit tests
        run: npm run citest
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
        # Run only once
        if: ${{ matrix.node == '20' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
